server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymybuddy
    username: root
    password: ""
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
