server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymybuddy
    username: root
    password: ""
  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

paymybuddy:
  backend:
    jwt-secret: cmFuZG9tU2VjcmV0
    expires-in: 600000
logging:
  level:
    root: INFO
    org.package: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

